Handling Missing Data

In [65]:
import pandas as pd
import numpy as np
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
print(string_data)

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object


In [66]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [67]:
string_data[0] = None

In [68]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

Filtering Out Missing Data

In [69]:
from numpy import nan as NA

In [70]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [71]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [72]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [73]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [74]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [75]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [76]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [77]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -0.283729       NaN       NaN
1 -0.778671       NaN       NaN
2  0.963807       NaN -0.901374
3 -1.417829       NaN -1.194907
4  0.963639  0.643320 -0.161172
5  1.719016 -0.749658 -0.932695
6  1.575354  0.635522  2.283143

In [78]:
df.dropna()
df.dropna(thresh=2)

0         1         2
2  0.963807       NaN -0.901374
3 -1.417829       NaN -1.194907
4  0.963639  0.643320 -0.161172
5  1.719016 -0.749658 -0.932695
6  1.575354  0.635522  2.283143

Filling Missing Data

In [79]:
df.fillna(0)

0         1         2
0 -0.283729  0.000000  0.000000
1 -0.778671  0.000000  0.000000
2  0.963807  0.000000 -0.901374
3 -1.417829  0.000000 -1.194907
4  0.963639  0.643320 -0.161172
5  1.719016 -0.749658 -0.932695
6  1.575354  0.635522  2.283143

In [80]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.283729  0.500000  0.000000
1 -0.778671  0.500000  0.000000
2  0.963807  0.500000 -0.901374
3 -1.417829  0.500000 -1.194907
4  0.963639  0.643320 -0.161172
5  1.719016 -0.749658 -0.932695
6  1.575354  0.635522  2.283143

In [81]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0 -0.283729  0.000000  0.000000
1 -0.778671  0.000000  0.000000
2  0.963807  0.000000 -0.901374
3 -1.417829  0.000000 -1.194907
4  0.963639  0.643320 -0.161172
5  1.719016 -0.749658 -0.932695
6  1.575354  0.635522  2.283143

In [82]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  1.619291  0.045628 -2.370765
1  1.624994  0.691679 -1.147346
2 -0.737495       NaN  0.214828
3 -0.392609       NaN -1.134169
4  0.967952       NaN       NaN
5 -0.626927       NaN       NaN

In [83]:
df.fillna(method='ffill')

0         1         2
0  1.619291  0.045628 -2.370765
1  1.624994  0.691679 -1.147346
2 -0.737495  0.691679  0.214828
3 -0.392609  0.691679 -1.134169
4  0.967952  0.691679 -1.134169
5 -0.626927  0.691679 -1.134169

In [84]:
df.fillna(method='ffill', limit=2)

0         1         2
0  1.619291  0.045628 -2.370765
1  1.624994  0.691679 -1.147346
2 -0.737495  0.691679  0.214828
3 -0.392609  0.691679 -1.134169
4  0.967952       NaN -1.134169
5 -0.626927       NaN -1.134169

In [85]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

Data Transformation

In [86]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [87]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [88]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [89]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [90]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

Transforming Data Using a Function or Mapping

In [91]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [92]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [93]:
meat_to_animal = {
 'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'
}

In [94]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [95]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

Replacing Values

In [96]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [97]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [98]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [99]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [100]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

Renaming Axis Indexes

In [101]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'], columns=['one', 'two', 'three', 'four'])

In [102]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [103]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [104]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [105]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [106]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

Discretization and Binning

In [107]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] 

In [108]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [109]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [110]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [111]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [112]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [113]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [114]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.011, 0.25], (0.5, 0.74], (0.5, 0.74], (0.74, 0.98], (0.74, 0.98], ..., (0.74, 0.98], (0.25, 0.5], (0.5, 0.74], (0.5, 0.74], (0.011, 0.25]]
Length: 20
Categories (4, interval[float64, right]): [(0.011, 0.25] < (0.25, 0.5] < (0.5, 0.74] < (0.74, 0.98]]

In [115]:
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, 4) # Cut into quartiles
cats

[(0.718, 3.283], (0.718, 3.283], (-0.689, 0.0278], (-3.15, -0.689], (0.718, 3.283], ..., (0.0278, 0.718], (-0.689, 0.0278], (0.718, 3.283], (0.718, 3.283], (0.0278, 0.718]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.15, -0.689] < (-0.689, 0.0278] < (0.0278, 0.718] < (0.718, 3.283]]

In [116]:
pd.value_counts(cats)

(-3.15, -0.689]     250
(-0.689, 0.0278]    250
(0.0278, 0.718]     250
(0.718, 3.283]      250
Name: count, dtype: int64

In [117]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(1.404, 3.283], (0.0278, 1.404], (-1.281, 0.0278], (-1.281, 0.0278], (0.0278, 1.404], ..., (0.0278, 1.404], (-1.281, 0.0278], (0.0278, 1.404], (1.404, 3.283], (0.0278, 1.404]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.15, -1.281] < (-1.281, 0.0278] < (0.0278, 1.404] < (1.404, 3.283]]

Detecting and Filtering Outliers

In [118]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.002109    -0.029319    -0.014913    -0.009892
std       1.035358     1.011639     0.988431     0.994566
min      -3.042567    -3.308751    -3.349442    -2.988063
25%      -0.702651    -0.726416    -0.734454    -0.654705
50%      -0.016798    -0.006119     0.018235    -0.019434
75%       0.707021     0.654224     0.687792     0.650601
max       3.414588     3.224017     3.359756     2.978665

In [119]:
col = data[2]
col[np.abs(col) > 3]

234    3.338039
375    3.359756
764   -3.349442
Name: 2, dtype: float64

In [120]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.001248    -0.029184    -0.015262    -0.009892
std       1.032488     1.009835     0.985053     0.994566
min      -3.000000    -3.000000    -3.000000    -2.988063
25%      -0.702651    -0.726416    -0.734454    -0.654705
50%      -0.016798    -0.006119     0.018235    -0.019434
75%       0.707021     0.654224     0.687792     0.650601
max       3.000000     3.000000     3.000000     2.978665

In [121]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1 -1.0  1.0 -1.0  1.0
2 -1.0  1.0  1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4 -1.0 -1.0  1.0 -1.0

Permutation and Random Sampling

In [122]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([3, 0, 1, 4, 2])

In [123]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [124]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11

In [125]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [126]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

4    4
0    5
3    6
4    4
2   -1
4    4
2   -1
0    5
3    6
3    6
dtype: int64

Computing Indicator/Dummy Variables

In [127]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
In [110]: pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [128]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [129]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [130]:
values = np.random.rand(10)
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

String Object Methods

In [131]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [132]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [133]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [134]:
'::'.join(pieces)

'a::b::guido'

In [135]:
'guido' in val

True

In [136]:
val.index(',')

1

In [137]:
val.find(':')

-1

In [138]:
val.index(':')

ValueError: substring not found

In [139]:
val.count(',')

2

In [140]:
val.replace(',', '::')

'a::b:: guido'

In [141]:
val.replace(',', '')

'ab guido'

Regular Expressions

In [142]:
import re
text = "foo bar\t baz \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [143]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [144]:
regex.findall(text)

[' ', '\t ', ' \t']

In [145]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [146]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [147]:
text[m.start():m.end()]

'dave@google.com'

In [148]:
print(regex.match(text))

None


In [149]:
print(regex.sub('REDACTED', text))
Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

SyntaxError: invalid syntax (1272225175.py, line 2)

In [150]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [151]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [152]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [153]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))
Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

SyntaxError: invalid syntax (3045492257.py, line 2)

Vectorized String Functions in pandas

In [154]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [155]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [156]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [157]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [158]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [159]:
mat = data.str.match(pattern, flags=re.IGNORECASE)
mat

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [161]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object