The NumPy ndarray: A Multidimensional Array Object

In [17]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 1.33125675, -1.27838399, -0.08869723],
       [-0.3197662 , -1.38511949,  1.92844562]])

In [18]:
data * 10

array([[ 13.31256748, -12.78383994,  -0.88697227],
       [ -3.19766202, -13.8511949 ,  19.2844562 ]])

In [19]:
data + data

array([[ 2.6625135 , -2.55676799, -0.17739445],
       [-0.6395324 , -2.77023898,  3.85689124]])

In [20]:
data.shape

(2, 3)

In [21]:
data.dtype

dtype('float64')

Creating ndarrays

In [22]:
data1 = [6, 7.5, 8, 0, 1]

In [23]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [24]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [25]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr2.ndim

2

In [27]:
arr2.dtype

dtype('int32')

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.empty((2, 3, 2))

array([[[1.01855798e-312, 1.08221785e-312],
        [1.03977794e-312, 9.54898106e-313],
        [1.16709769e-312, 1.03977794e-312]],

       [[1.23075756e-312, 1.08221785e-312],
        [1.06099790e-312, 9.76118064e-313],
        [1.18831764e-312, 1.90979621e-312]]])

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Data Types for ndarrays

In [32]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [33]:
arr2.dtype

dtype('int32')

In [34]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [36]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

Arithmetic with NumPy Arrays

In [39]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [41]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [43]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [44]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [45]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Basic Indexing and Slicing

In [47]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[5]

5

In [49]:
arr[5:8]

array([5, 6, 7])

In [50]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [51]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [52]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [53]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [54]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [55]:
arr2d[0][2]

3

In [56]:
arr2d[0, 2]

3

In [57]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[1, 0]


array([7, 8, 9])

In [62]:
x = arr3d[1]

In [63]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [65]:
x[0]

array([7, 8, 9])

In [66]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [67]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [68]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [72]:
arr2d[1, :2]

array([4, 5])

In [73]:
arr2d[:2, 2]

array([3, 6])

In [74]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [75]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

Boolean Indexing

In [76]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [77]:
data

array([[-0.92956554,  0.55461393,  0.66482423, -0.27606304],
       [ 0.69278213,  0.00337425,  0.38584137,  0.96393076],
       [-0.62619245,  0.50402855, -0.07063079, -0.97628064],
       [-1.22133396, -1.11707035,  1.06021001, -0.1105593 ],
       [ 0.28827078, -1.97813179, -2.16935609,  0.28595689],
       [ 0.03533858, -0.1995004 , -1.36740864,  0.92723066],
       [ 1.22716275, -0.83390232, -0.34173325, -0.94082338]])

In [78]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [79]:
data[names == 'Bob']

array([[-0.92956554,  0.55461393,  0.66482423, -0.27606304],
       [-1.22133396, -1.11707035,  1.06021001, -0.1105593 ]])

In [80]:
data[names == 'Bob', 2:]

array([[ 0.66482423, -0.27606304],
       [ 1.06021001, -0.1105593 ]])

In [81]:
data[names == 'Bob', 3]

array([-0.27606304, -0.1105593 ])

In [82]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [83]:
data[~(names == 'Bob')]

array([[ 0.69278213,  0.00337425,  0.38584137,  0.96393076],
       [-0.62619245,  0.50402855, -0.07063079, -0.97628064],
       [ 0.28827078, -1.97813179, -2.16935609,  0.28595689],
       [ 0.03533858, -0.1995004 , -1.36740864,  0.92723066],
       [ 1.22716275, -0.83390232, -0.34173325, -0.94082338]])

In [84]:
cond = names == 'Bob'
data[~cond]

array([[ 0.69278213,  0.00337425,  0.38584137,  0.96393076],
       [-0.62619245,  0.50402855, -0.07063079, -0.97628064],
       [ 0.28827078, -1.97813179, -2.16935609,  0.28595689],
       [ 0.03533858, -0.1995004 , -1.36740864,  0.92723066],
       [ 1.22716275, -0.83390232, -0.34173325, -0.94082338]])

In [85]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [86]:
data[mask]

array([[-0.92956554,  0.55461393,  0.66482423, -0.27606304],
       [-0.62619245,  0.50402855, -0.07063079, -0.97628064],
       [-1.22133396, -1.11707035,  1.06021001, -0.1105593 ],
       [ 0.28827078, -1.97813179, -2.16935609,  0.28595689]])

In [87]:
data[data < 0] = 0
data

array([[0.        , 0.55461393, 0.66482423, 0.        ],
       [0.69278213, 0.00337425, 0.38584137, 0.96393076],
       [0.        , 0.50402855, 0.        , 0.        ],
       [0.        , 0.        , 1.06021001, 0.        ],
       [0.28827078, 0.        , 0.        , 0.28595689],
       [0.03533858, 0.        , 0.        , 0.92723066],
       [1.22716275, 0.        , 0.        , 0.        ]])

In [88]:
data[names != 'Joe'] = 7
data

array([[7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [6.92782125e-01, 3.37424874e-03, 3.85841367e-01, 9.63930764e-01],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [3.53385797e-02, 0.00000000e+00, 0.00000000e+00, 9.27230656e-01],
       [1.22716275e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

Fancy Indexing

In [89]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [90]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [91]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [92]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [93]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [94]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Transposing Arrays and Swapping Axes

In [96]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [97]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [98]:
arr = np.random.randn(6, 3)
arr

array([[-0.64463507,  0.14070073, -1.36621636],
       [ 0.78082674,  0.63840542,  0.00261198],
       [ 0.30600253,  0.30494517, -0.67027836],
       [-1.25979627,  1.6192083 ,  0.63251084],
       [-0.118179  ,  0.39663229,  0.19999629],
       [ 1.63626756,  0.37443861,  2.15160421]])

In [99]:
np.dot(arr.T, arr)

array([[ 5.39730674, -0.97296703,  3.3777736 ],
       [-0.97296703,  3.4397067 ,  1.5141772 ],
       [ 3.3777736 ,  1.5141772 ,  7.38529618]])

In [100]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [101]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [102]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [103]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

Universal Functions: Fast Element-Wise Array Functions

In [105]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [107]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [108]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.79983253,  1.82515907,  0.8951699 ,  1.41970342,  0.65135153,
        1.17142372, -0.96212208,  2.33697189])

In [109]:
y

array([ 0.56257412, -1.1396194 , -0.13137556, -0.8532444 , -1.83051697,
       -0.64128068, -0.22582855,  0.24199658])

In [110]:
np.maximum(x, y)

array([ 0.79983253,  1.82515907,  0.8951699 ,  1.41970342,  0.65135153,
        1.17142372, -0.22582855,  2.33697189])

In [111]:
arr = np.random.randn(7) * 5
arr

array([2.4513882 , 4.57266608, 2.02430713, 3.52458283, 4.37553572,
       4.15656546, 0.85526552])

In [112]:
remainder, whole_part = np.modf(arr)
remainder

array([0.4513882 , 0.57266608, 0.02430713, 0.52458283, 0.37553572,
       0.15656546, 0.85526552])

In [113]:
whole_part

array([2., 4., 2., 3., 4., 4., 0.])

In [114]:
arr

array([2.4513882 , 4.57266608, 2.02430713, 3.52458283, 4.37553572,
       4.15656546, 0.85526552])

In [115]:
np.sqrt(arr)

array([1.56569096, 2.13837931, 1.42278148, 1.87738724, 2.09177812,
       2.03876567, 0.92480566])

In [116]:
np.sqrt(arr, arr)

array([1.56569096, 2.13837931, 1.42278148, 1.87738724, 2.09177812,
       2.03876567, 0.92480566])

In [117]:
arr

array([1.56569096, 2.13837931, 1.42278148, 1.87738724, 2.09177812,
       2.03876567, 0.92480566])